In [1]:
x = np.array([1,2,3])

In [2]:
A = np.arange(1,10).reshape(3,3)

In [3]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
x.T @ A @ x

228

In [5]:
A = (np.arange(9) - 4).reshape((3,3))

In [6]:
A

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [7]:
np.linalg.norm(A)

7.745966692414834

In [8]:
np.trace(np.eye(3))

3.0

In [15]:
A = (np.arange(9) + 1).reshape((3,3))

In [16]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.linalg.det(A)

0.0

In [12]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [13]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
np.linalg.det(A)

0.0