In [4]:
x = np.array([1,2,3])

In [5]:
A = np.arange(1,10).reshape(3,3)

In [6]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
x.T @ A @ x

228

In [8]:
A = (np.arange(9) - 4).reshape((3,3))

In [9]:
A

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [10]:
np.linalg.norm(A)

7.745966692414834

In [11]:
np.trace(np.eye(3))

3.0

In [12]:
A = (np.arange(9) + 1).reshape((3,3))

In [13]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.linalg.det(A)

0.0

In [15]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [16]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.linalg.det(A)

0.0

In [19]:
Ainv = np.array([[1,1,0], [0,1,1], [1,1,1]])

In [22]:
Ainv = np.linalg.inv(Ainv)

In [23]:
Ainv

array([[ 0., -1.,  1.],
       [ 1.,  1., -1.],
       [-1.,  0.,  1.]])

In [24]:
A = np.array([[1,1,0], [0,1,1], [1,1,1]])

In [25]:
Ainv = np.linalg.inv(A
                    )

In [26]:
b = np.array([[2], [2], [3]])

In [27]:
x = Ainv @ b

In [28]:
x

array([[1.],
       [1.],
       [1.]])

In [29]:
A @ x -b 

array([[0.],
       [0.],
       [0.]])

In [30]:
x, resid, rank, s = np.linalg.lstsq(A,b)

In [31]:
x

array([[1.],
       [1.],
       [1.]])

In [33]:
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target
A = X[:4, [0,4,5,6]]
b = y[:4]

In [34]:
A
b

array([24. , 21.6, 34.7, 33.4])

In [35]:
A

array([[6.320e-03, 5.380e-01, 6.575e+00, 6.520e+01],
       [2.731e-02, 4.690e-01, 6.421e+00, 7.890e+01],
       [2.729e-02, 4.690e-01, 7.185e+00, 6.110e+01],
       [3.237e-02, 4.580e-01, 6.998e+00, 4.580e+01]])

In [36]:
b

array([24. , 21.6, 34.7, 33.4])

In [38]:
x, redis, rank, s = np.linalg.lstsq(A, b)

In [39]:
x

array([-3.12710043e+02, -1.15193942e+02,  1.44996465e+01, -1.13259317e-01])